databases:
  - name: Automatic_Fuel_Management_System
    databaseName: Automatic_Fuel_Management_System
    user: lakshan

services:
  - type: web
    name: Automatic_Fuel_Management_System
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn automatic_fuel_management_system.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Automatic_Fuel_Management_System
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4