# Generated by Django 4.0.6 on 2022-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vechicleusers',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
